//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialTransactionTextInterpreter.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialTransactionTextInterpreter.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction text should contain at least one and no more than two accounts..
        /// </summary>
        public static string ErrorMessage_InformationAboutAccountsNumberInTransaction {
            get {
                return ResourceManager.GetString("ErrorMessage_InformationAboutAccountsNumberInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items need to have category written before them..
        /// </summary>
        public static string ErrorMessage_InformationAboutCategoryRequirementForItems {
            get {
                return ResourceManager.GetString("ErrorMessage_InformationAboutCategoryRequirementForItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction text contains too many contractors..
        /// </summary>
        public static string ErrorMessage_InformationAboutContractorsNumber {
            get {
                return ResourceManager.GetString("ErrorMessage_InformationAboutContractorsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format should be dd-MM-yyyy..
        /// </summary>
        public static string ErrorMessage_InformationAboutDateFormat {
            get {
                return ResourceManager.GetString("ErrorMessage_InformationAboutDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing was not done yet..
        /// </summary>
        public static string ErrorMessage_ProcessingWasNotDoneYet {
            get {
                return ResourceManager.GetString("ErrorMessage_ProcessingWasNotDoneYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction text is empty..
        /// </summary>
        public static string ErrorMessage_TransactionTextIsEmpty {
            get {
                return ResourceManager.GetString("ErrorMessage_TransactionTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred when processing transaction..
        /// </summary>
        public static string ErrorMessage_UnexpectedErrorWhenProcessing {
            get {
                return ResourceManager.GetString("ErrorMessage_UnexpectedErrorWhenProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Transaction with item names:
        ///
        ///&amp;22-04-2024 $Wallet #Food roll 2.2 2.2 +0.4 ham 3.3 #Craving bar 4.5 @Frog.
        ///
        ///From this text, a transaction will be created with a contractor named Frog, concluded on April 22, 2024, which was paid from an account named wallet. The elements of this transaction will be created: a roll with a price - 4 and a food category, a ham with a price - 3.3 and a food category, and a bar with a price - 4.5 and a craving category.
        ///- Transaction without item names
        ///
        ///&amp;22-04-2024 $Bank  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpBoxView_ExamplesSectionContent {
            get {
                return ResourceManager.GetString("HelpBoxView_ExamplesSectionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string HelpBoxView_ExamplesSectionTitle {
            get {
                return ResourceManager.GetString("HelpBoxView_ExamplesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions:
        ///- Transaction - transaction/action done with external contractor: shop, employer, account outside your system.
        ///- Transfer - transaction/action done between internal accounts like from cash to bank. 
        ///- Tag - character in the beginning of word used to determine kind of data to assign it. 
        ///
        ///Features:
        ///- Each element of the transaction is assigned the nearest preceding category.
        ///- All words without a tag and that are not numbers are treated as the name of the transaction element. If there is  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpBoxView_GeneralHelpSectionContent {
            get {
                return ResourceManager.GetString("HelpBoxView_GeneralHelpSectionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpBoxView_GeneralHelpSectionTitle {
            get {
                return ResourceManager.GetString("HelpBoxView_GeneralHelpSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &amp; - date. One date per transaction/transfer.
        ///- $ - account. Only one account can be indicated in a transaction. In a transfer two: source and destination. The flow of money is determined by the character &apos;&gt;
        ///- # - category. It can be entered only for a transaction. Any item entered after the category will belong to it&apos;.
        ///- @ - counterparty. One counterparty per transaction and only in a transaction can be entered.
        ///- + - used in transactions/transfers to specify revenue. By default all numbers are treate [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpBoxView_TagsSectionContent {
            get {
                return ResourceManager.GetString("HelpBoxView_TagsSectionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string HelpBoxView_TagsSectionTitle {
            get {
                return ResourceManager.GetString("HelpBoxView_TagsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to apply the new language..
        /// </summary>
        public static string LanguageSelector_MessageBoxContent {
            get {
                return ResourceManager.GetString("LanguageSelector_MessageBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string LanguageSelector_MessageBoxTitle {
            get {
                return ResourceManager.GetString("LanguageSelector_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear text.
        /// </summary>
        public static string PromptInput_ClearTextButton {
            get {
                return ResourceManager.GetString("PromptInput_ClearTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PromptInput_ProcessTextButton {
            get {
                return ResourceManager.GetString("PromptInput_ProcessTextButton", resourceCulture);
            }
        }
    }
}
