# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_PATH: WpfFinancialTransactionPromptInterpreter/WpfFinancialTransactionPromptInterpreter.csproj

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore
    - name: Publish
      run: dotnet publish ${{env.PROJECT_PATH}} /p:PublishProfile=WpfFinancialTransactionPromptInterpreter\Properties\PublishProfiles\FolderProfile.pubxml --no-build
    
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ReleaseTest
        release_name: Release test
        body: |
          Changes in this Release
    - name: Upload Project
      uses: csexton/release-asset-action@v2    
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pattern: WpfFinancialTransactionPromptInterpreter/Release/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}