name: TransactionPromptInterpreter build and publish as Single File

on:
  push:
    branches: [ "master" ]
    tags: 
      - "Release_*.*.*"
    
env:
  ProjectPath: WpfFinancialTransactionPromptInterpreter
  ProjectName: WpfFinancialTransactionPromptInterpreter.csproj

jobs:
  prepareVersionTag:
    runs-on: windows-latest
    name: Extract release version from tag
    steps:
      - run: |
            $pattern = '[0-9]+\.[0-9]+\.[0-9]+'     
            if(${{ github.ref_name }} -match $pattern){
            "releaseVersion=$matches[1]" | Out-File -FilePath $env:GITHUB_ENV -Append
            } else {
            Write-Output "No release number"
            exit 1
            }     
    
  build:
    name: Build TransactionPromptInterpreter app
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
          
    - name: Publish
      run: dotnet publish ${{env.ProjectPath}}\${{env.ProjectName}} /p:PublishProfile=${{env.ProjectPath}}\Properties\PublishProfiles\FolderProfile.pubxml
     
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create 0.0.2 
