name: TransactionPromptInterpreter build and publish as Single File

on:
  push:
    branches: [ "master" ]
    
env:
  ProjectPath: WpfFinancialTransactionPromptInterpreter
  ProjectName: WpfFinancialTransactionPromptInterpreter.csproj

jobs:  
  build:
    name: Build TransactionPromptInterpreter App
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build 
      run: dotnet build ${{env.ProjectPath}}\${{env.ProjectName}} -c Release --no-restore
  publish:
    name: Publish Single File App
    needs: build
    runs-on: windows-latest
    steps:
    - name: Publish
      run: dotnet publish ${{env.ProjectPath}}\${{env.ProjectName}} /p:PublishProfile=${{env.ProjectPath}}\Properties\PublishProfiles\FolderProfile.pubxml
  release:
    name: Create release
    needs: publish
    runs-on: windows-latest
    steps:
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create ${{ github.sha }} ${{env.ProjectPath}}/bin/Publish/*.exe
