name: TransactionPromptInterpreter build and publish as Single File

on:
  push:
    branches: [ "master" ]
    
env:
  ProjectPath: FinancialTransactionTextInterpreter
  ProjectName: FinancialTransactionTextInterpreter.csproj

jobs:  
  job:
    name: Build, publish and create Release
    runs-on: windows-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build and publish
      run: dotnet publish ${{env.ProjectPath}}\${{env.ProjectName}} /p:PublishProfile=${{env.ProjectPath}}\Properties\PublishProfiles\FolderProfile.pubxml
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $time = Get-Date -Format "yyyy-MM-dd_HH-mm" 
        Write-Host "Current time: $time"
        $compress = @{
          Path = "FinancialTransactionTextInterpreter/FinancialData.xlsx", "FinancialTransactionTextInterpreter/bin/Publish/FinancialTransactionTextInterpreter.exe"
          CompressionLevel = "Fastest"
          DestinationPath = "FinancialTransactionTextInterpreter/bin/Publish/AppWithExcelTemplate.zip"
        }
        Compress-Archive @compress
        Write-Host "Files Compressed successfully."
        $filesToInclude = @('FinancialTransactionTextInterpreter/bin/Publish/FinancialTransactionTextInterpreter.exe' , 'FinancialTransactionTextInterpreter/bin/Publish/AppWithExcelTemplate.zip')
        gh release create $time $filesToInclude
        Write-Host "Release created successfully."

