# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ProjectPath: WpfFinancialTransactionPromptInterpreter
  ProjectName: WpfFinancialTransactionPromptInterpreter.csproj

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore
    - name: Publish
      run:  dotnet publish ${{env.ProjectPath}}\${{env.ProjectName}} /p:PublishProfile=${{env.ProjectPath}}\Properties\PublishProfiles\FolderProfile.pubxml --no-build
    - run: |
        ls 
        ls WpfFinancialTransactionPromptInterpreter
        ls WpfFinancialTransactionPromptInterpreter/bin
        ls WpfFinancialTransactionPromptInterpreter/bin/Publish
    
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create testever WpfFinancialTransactionPromptInterpreter/bin/Publish/WpfFinancialTransactionPromptInterpreter.exe
