name: TransactionPromptInterpreter build and publish as Single File

on:
  push:
    branches: [ "master" ]
    
env:
  ProjectPath: WpfFinancialTransactionPromptInterpreter
  ProjectName: WpfFinancialTransactionPromptInterpreter.csproj

jobs:  
  job:
    name: Build, publish and create Release
    runs-on: windows-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build 
      run: dotnet build ${{env.ProjectPath}}\${{env.ProjectName}} -c Release --no-restore
    - run: |
        ls
        ls ${{env.ProjectPath}}
        ls ${{env.ProjectPath}}\Properties
        ls ${{env.ProjectPath}}\Properties\PublishProfiles
    - name: Publish
      run: dotnet publish ${{env.ProjectPath}}\${{env.ProjectName}} /p:PublishProfile=${{env.ProjectPath}}\Properties\PublishProfiles\FolderProfile.pubxml --no-build
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create ${{ github.sha }} WpfFinancialTransactionPromptInterpreter/bin/Publish/WpfFinancialTransactionPromptInterpreter.exe
